export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH = 'FETCH';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const LIKE = 'LIKE';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

//USERS
export const FETCH_USERS = 'FETCH_USERS';

//POSTS
export const FETCH_POST = 'FETCH_POST';
export const FETCH_POSTS = 'FETCH_POSTS';

//CONVERSATION
export const FETCH_CONVERSATION = 'FETCH_CONVERSATION';
export const FETCH_CONVERSATIONS = 'FETCH_CONVERSATIONS';
export const SET_CONVERSATION_ID = 'SET_CONVERSATION';
export const GET_CONVERSATION_ID = 'GET_CONVERSATION';
export const SET_CONVERSATION_WITH = 'SET_CONVERSATION_WITH';
export const CREATE_CONVERSATION = 'CREATE_CONVERSATION';
export const CREATE_CONVERSATION_AND_MESSAGE = 'CREATE_CONVERSATION_AND_MESSAGE';
export const RESET_CONVERSATION_DATA = 'RESET_CONVERSATION_DATA';

//MESSAGE
export const FETCH_MESSAGE = 'FETCH_MESSAGE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const RESET_MESSAGES = 'RESET_MESSAGES';

//NEW
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
